# INTRODUCTION

Big Data Sentiment Analysis is the process of analyzing text data to determine whether the sentiment is positive, negative, or neutral.

This project performs sentiment analysis on sample text data using Python and TextBlob library.

#OBJECTIVES

- To analyze text sentiments
- To classify sentiments as positive, negative, or neutral
- To use Python libraries for sentiment analysis
- To understand text processing techniques

# TOOLS USED

- Python
- Pandas
- TextBlob
- Google Colab
- GitHub

In [1]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

IMPORT LIBRARIES

In [2]:
# IMPORT LIBRARIES

import pandas as pd
from textblob import TextBlob

In [3]:
# SAMPLE TEXT DATA

texts = [
    "I love this product",
    "This is a terrible experience",
    "The service was okay",
    "Amazing performance and great quality",
    "I am very disappointed"
]

df = pd.DataFrame(texts, columns=['Text'])

df

                                    Text
0                    I love this product
1          This is a terrible experience
2                   The service was okay
3  Amazing performance and great quality
4                 I am very disappointed

In [4]:
# SENTIMENT ANALYSIS

def get_sentiment(text):

    analysis = TextBlob(text)

    polarity = analysis.sentiment.polarity

    if polarity > 0:
        return "Positive"

    elif polarity < 0:
        return "Negative"

    else:
        return "Neutral"

df['Sentiment'] = df['Text'].apply(get_sentiment)

df

                                    Text Sentiment
0                    I love this product  Positive
1          This is a terrible experience  Negative
2                   The service was okay  Positive
3  Amazing performance and great quality  Positive
4                 I am very disappointed  Negative

# CONCLUSION

- Text sentiments were analyzed successfully
- Positive, Negative, and Neutral sentiments were identified
- TextBlob library was used for sentiment analysis
- Sentiment analysis helps understand user opinions from text data